apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: "$.ns"
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: k3env/landing-cv-admin:$.tag
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
